### ISSUE TITLE
Crash on sounds played with exponential release

### ISSUE THREAD

**Issue by GameDevZach** [byersdz/bitmelo#10]
"DOMException: AudioParam.exponentialRampToValueAtTime: Previous event value must be positive"
traced to Audio.js:157
I'm using Firefox, and it happens as you release the pressed key when playing a sound with exponential release.

**Comment by byersdz** [comment]
Was this in the editor, or in the built game? Any chance you could send me the project file?

**Comment by byersdz** [comment]
nvm don't need the project yea I see it happening

**Comment by byersdz** [comment]
Fixed now  :)
