### ISSUE TITLE
Tiles in the rows greater than the tileset width do not display when running

### ISSUE THREAD

**Issue by StaticJFrame** [byersdz/bitmelo#2]
When you have a tileset with a greater height than width, the tiles in the rows greater than the maximum number of columns do not display when running the game (both in the editor, and when exporting the game).

![image](https://user-images.githubusercontent.com/53121788/65375792-4a6e5e00-dc67-11e9-8b07-ec102127900f.png)
Tilemap made with a 7x8 tileset

![image](https://user-images.githubusercontent.com/53121788/65375829-902b2680-dc67-11e9-92ca-37af2b695cf1.png)
Render of the map during runtime (notice the pink tile is missing)

[Tilemap Render Issue.project.txt](https://github.com/byersdz/bitmelo/files/3638841/Tilemap.Render.Issue.project.txt)
Project File (rename to .json, just clears the background and draws the tileset)

This occurs both when performing the map draw and the individual tile draw. The projects save and load fine, and appear in the editor, but just not when running the game.

I'll be trying to solve this myself, but posting it here in case anyone else runs into a similar issue or finds a solution first.

**Comment by byersdz** [comment]
So it turns out this was an issue in the editor. Will be fixed in the next version.
